# Generated by Django 3.2.7 on 2021-12-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debris',
            fields=[
                ('name', models.CharField(max_length=24)),
                ('tle_1', models.CharField(max_length=80)),
                ('tle_2', models.CharField(max_length=80)),
                ('norad', models.IntegerField(primary_key=True, serialize=False)),
                ('classification', models.CharField(max_length=1)),
                ('international_designation', models.CharField(max_length=6)),
                ('epoch_year', models.IntegerField()),
                ('epoch_day', models.DecimalField(decimal_places=8, max_digits=11)),
                ('first_derivative_mean_motion', models.DecimalField(decimal_places=9, max_digits=10)),
                ('second_derivative_mean_motion', models.DecimalField(decimal_places=9, max_digits=10)),
                ('bstar', models.DecimalField(decimal_places=10, max_digits=10)),
                ('set_number', models.IntegerField()),
                ('inclination', models.DecimalField(decimal_places=4, max_digits=10)),
                ('raan', models.DecimalField(decimal_places=4, max_digits=10)),
                ('eccentricity', models.DecimalField(decimal_places=10, max_digits=20)),
                ('argp', models.DecimalField(decimal_places=4, max_digits=10)),
                ('mean_anomaly', models.DecimalField(decimal_places=4, max_digits=10)),
                ('mean_motion', models.DecimalField(decimal_places=8, max_digits=10)),
                ('type', models.CharField(default='debris', max_length=16)),
            ],
        ),
    ]
