# Generated by Django 3.2.7 on 2021-09-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('long', models.DecimalField(decimal_places=2, max_digits=3)),
                ('lat', models.DecimalField(decimal_places=2, max_digits=3)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
