# Generated by Django 3.2.7 on 2021-09-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='lat',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='long',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
