# Generated by Django 3.2.7 on 2021-10-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='first_derivative_mean_motion',
            field=models.DecimalField(decimal_places=9, max_digits=10),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='second_derivative_mean_motion',
            field=models.DecimalField(decimal_places=9, max_digits=10),
        ),
    ]
