# Generated by Django 3.2.7 on 2021-09-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellite', '0002_auto_20210917_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satellite',
            name='active',
        ),
        migrations.RemoveField(
            model_name='satellite',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='satellite',
            name='long',
        ),
        migrations.AddField(
            model_name='satellite',
            name='tle_1',
            field=models.CharField(default='1 00900U 64063C   21260.37098799  .00000233  00000-0  23859-3 0  9999', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='satellite',
            name='tle_2',
            field=models.CharField(default='2 00900  90.1673  36.0207 0029341 122.4344 269.7150 13.73585461833179', max_length=80),
            preserve_default=False,
        ),
    ]
