# Generated by Django 3.2.7 on 2021-09-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellite', '0003_auto_20210918_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
