# Generated by Django 3.2.7 on 2021-12-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellite', '0003_auto_20211107_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='country',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='launch_date',
            field=models.CharField(blank=True, default='0000-00-00', max_length=10),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='launch_site',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='object_status',
            field=models.CharField(blank=True, default='Operational', max_length=32),
        ),
    ]
