# Generated by Django 3.2.7 on 2021-12-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellite', '0005_satellite_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
